torchrun --nproc_per_node=8 --master_port=29400 train.py \
    --model_name_or_path ./llama-hf \
    --data_path ./alpaca_data_sample.json \
    --bf16 True \
    --output_dir ./output_dir_llama_test \
    --num_train_epochs 3 \
    --per_device_train_batch_size 2 \
    --per_device_eval_batch_size 2 \
    --gradient_accumulation_steps 1 \
    --evaluation_strategy "no" \
    --save_strategy "epoch" \
    --save_total_limit 3 \
    --learning_rate 2e-5 \
    --weight_decay 0. \
    --warmup_ratio 0.03 \
    --lr_scheduler_type "cosine" \
    --logging_steps 1 \
    --fsdp "full_shard auto_wrap" \
    --fsdp_config "fsdp_config.json" \
    --tf32 True
